### ISSUE TITLE
Bot tries to send reply to original chat for forwarded messages

### ISSUE THREAD

**Issue by BjoernPetersen** [preparingforexams/nhbot#57]
1. Send message `m` in chat `A`
2. Forward `m` to chat `B` (which has the bot as a member)
3. Bot tries to send meme to chat `A` (probably took that from `update.effective_message`)
4. Bot fails

```
[command_nh] 2023-05-22 11:39:01,602    DEBUG    decorators.wrapped_f#131 | End
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/telegram_bot/decorators.py", line 128, in wrapped_f
    raise e
  File "/usr/src/app/telegram_bot/decorators.py", line 117, in wrapped_f
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/telegram_bot/bot.py", line 153, in nh
    self.send_nh_sticker(chat=chat, message_id=update.effective_message.message_id)
  File "/usr/src/app/telegram_bot/bot.py", line 122, in send_nh_sticker
    self.updater.bot.send_sticker(chat_id=chat.id, sticker=sticker_id, reply_to_message_id=message_id)
  File "/usr/local/lib/python3.11/site-packages/telegram/bot.py", line 134, in decorator
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/bot.py", line 1083, in send_sticker
    return self._message(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/ext/extbot.py", line 203, in _message
    result = super()._message(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/bot.py", line 344, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/bot.py", line 299, in _post
    return self.request.post(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found

```

**Comment by torbencarstens** [comment]
Probably closed by e7af99ddb4060f4c25726dcddeefe5dc62ecee5f and 6e8d4e3dc030d45c71cb99beb55d7561f282206f
